spring:

  jpa:
    #hibernate.ddl-auto: create-drop
    hibernate.ddl-auto: validate
    # Disable feature detection by this undocumented parameter.
    #Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    # Because detection is disabled you have to set correct dialect by hand.
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    # allow lazy fetch without session
    open-in-view: true

  datasource:
    #url: jdbc:mysql://localhost:3306/workoutperf
    url: jdbc:postgresql://localhost:5432/workoutperf
    username: root
    password: admin
    testOnBorrow: true
    validationQuery: SELECT 1

  flyway:
    locations: classpath:db/migration/{vendor},classpath:db/migration/common
